data_root_dir: D:/backup/BreaKHis


data_ingestion:
  root_dir: data_ingestion
  compressed_file: D:/backup/BreaKHis_v1.tar.gz
  extract_dir: data_ingestion

data_split:
  root_dir: data_split
  train_dir: train
  test_dir: test
  val_dir: val

training:
  root_dir: training

models:
  root_dir: models
  model: model.h5